# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aee886010b862cbaf8962054563691d13790b8f1caccfe08ed6579fde6d3f08db6e61dd485d1d7ed7720532ffa4b7da834ac55ce44247e4768e444461c6eb7ea

test:
  secret_key_base: 3dfa62ad16e210def7f355619f23252e176538ced5a4f41ad3f9eed22b19af345f3b4a5da6fecf5aa310bee3434a309fedc0dd473cca09d29fb6364568afb2a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
